apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-prodcution-e2e-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complete-prodcution-e2e-app
  template:
    metadata:
      labels:
        app: complete-prodcution-e2e-app
    spec:
      containers:
      - name: app-container
        image: lukszyd/complete-prodcution-e2e-pipeline-github-actions:1.0.0-18
        ports:
        - containerPort: 8080