apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-prodcution-e2e-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: complete-prodcution-e2e-app
  template:
    metadata:
      labels:
        run: complete-prodcution-e2e-app
    spec:
      containers:
      - name: complete-prodcution-e2e-app
        image: lukszyd/complete-prodcution-e2e-pipeline-github-actions:latest
        resources:
         limits:
          memory: "256Mi"
          cpu: "500m"
        ports:
          - containerPort: 8080
