apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 5555
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: complete-prodcution-e2e-app