apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-app-service
spec:
  selector:
    app: complete-prodcution-e2e-app
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 8080
  type: NodePort  